feat: prevent continuous sending of codes
e-dialect/hinghwa-dict-uni-app pull request #169
Opened 2023-03-17 15:46 UTC by zzzYmq

对输入的邮箱进行验证，并且阻止用户连续发送验证码 close #23

2023-03-18 16:07 UTC, FrogDar commented
charlie_c_0129@outlook.com

这个邮箱貌似过不了测试？

![image](https://user-images.githubusercontent.com/20886330/226117580-7772ae45-5697-4d66-b9cf-c6ecf10eac40.png)

2023-03-18 16:08 UTC, FrogDar commented
sheeplin@bupt.edu.cn 也不行
![image](https://user-images.githubusercontent.com/20886330/226117716-b50d383f-fb4a-4019-90ed-64587b26fd97.png)

2023-03-19 10:14 UTC, zzzYmq commented
那我再测试修改一下

2023-03-20 10:24 UTC, FrogDar requested changes
既然要模块化 或许可以做的更彻底x
（功能上已经没有问题了）

2023-03-20 10:24 UTC, FrogDar commented on src/pages/login/register.vue
> +      const pattern = /^[a-z0-9]+([._\\-]*[a-z0-9])*@([a-z0-9]+[-a-z0-9]*[a-z0-9]+.){1,63}[a-z0-9]+$/;
如果都写成 mixin 的形式，为什么这个东西不放在里面呢？作为一个常量被别人调用？

2023-03-21 09:14 UTC, FrogDar requested changes

2023-03-21 09:14 UTC, FrogDar commented on src/pages/login/mixin/getCodeMixin.js
> +      pattern: /^[a-z0-9]+([._\\-]*[a-z0-9])*@([a-z0-9]+[-a-z0-9]*[a-z0-9]+.){1,63}[a-z0-9]+$/,
改革变量名吧 比如 mailPattern 之类的？ 要不然万一原本的页面有相关的命名呢？

2023-03-21 12:53 UTC, FrogDar approved these changes

2023-03-21 12:58 UTC, merged

2023-03-21 13:14 UTC, FrogDar commented on src/pages/login/mixin/getCodeMixin.js
> +          this.count -= 1;
实际上你要做的是 else  -= 1

直接return  return的也是回调函数，自然就和废话一样
格式化工具就吧废话删除了