添加亲戚计算器功能
e-dialect/hinghwa-dict-uni-app pull request #174
Opened 2023-05-03 10:26 UTC by zzy2695s

feat(relative): add relative calculation function
close #136

2023-05-03 10:28 UTC, zzy2695s commented
![image](https://user-images.githubusercontent.com/106298834/235891982-714fdebc-3f29-4cb1-8954-74042f06f414.png)
![image](https://user-images.githubusercontent.com/106298834/235891987-8c46239e-9c4e-49a7-9ddd-98348093cf47.png)
目前还有两个问题：一是刚加载页面时候不会显示“家己”这个词语，二是在H5编译不出来这个页面

2023-05-03 10:55 UTC, zzy2695s commented
修复no-await-in-loop lint警告我用了禁用规则注释，查了一下在这种情形下应该是可以用的

2023-05-03 11:40 UTC, FrogDar requested changes
H5的感觉也可以编译出来呀？

2023-05-03 11:40 UTC, FrogDar commented on src/components/WordListShowing.vue
>              </view>
再加一个跳转去创建词条的按钮吧

2023-05-03 11:40 UTC, FrogDar commented on src/pages/tools/relative.vue
> +
加一点灰色小字吧，类似于词语详情那边
就说正在测试中，有不对的可以去兔小巢反馈

2023-05-03 11:40 UTC, FrogDar commented on src/components/WordListShowing.vue
> +              反馈
然后这个东西可能不要那么显眼的大蓝色？

2023-05-03 11:40 UTC, FrogDar commented on src/pages/tools/relative.vue
> +      stack: [[relative[0]]],
如果第一个己身出不来的话，可以考虑把这里直接初始化为`[]`，然后在一个类似于 `created` 事件中 赋值一下什么的

2023-05-10 09:46 UTC, zzy2695s commented
问题已经修好啦 
反馈改成了这样
![image](https://github.com/e-dialect/hinghwa-dict-uni-app/assets/106298834/aeb527d4-d550-413f-a60e-bd9d4e7774dd)
初始化的问题用了学长说的方法，在onload加了push和pop，但是一直不太行，所以换了种方法
![image](https://github.com/e-dialect/hinghwa-dict-uni-app/assets/106298834/23e4a22c-1d81-46a8-bbde-f68f2ca21459)

2023-05-13 08:02 UTC, FrogDar approved these changes

2023-05-13 08:02 UTC, FrogDar approved these changes

2023-05-13 08:03 UTC, merged