feat(mail): add mail system
e-dialect/hinghwa-dict-uni-app pull request #181
Opened 2023-08-17 15:08 UTC by daonan233

This is a mail feature

2023-08-18 14:34 UTC, FrogDar commented on src/pages/tools/mail.vue
> +    </view>
暂时注释掉这个功能，短期内不上线

2023-08-18 14:36 UTC, FrogDar commented on src/pages/tools/sendmail.vue
> +        >
可以开个issue，列一个待办，以后应该是根据输入的内容自动搜索用户（发送的时候这里还是发的id，但是显示的时候是一个下拉列表然后选中某个用户，考虑支持多选？）
（不过邮件互相发送这个功能很晚才弄，这个虽然可以留着但是短期内不上线

2023-09-03 17:44 UTC, FrogDar commented
邮箱功能很多都是归档好就可以放着了
（归档：代码归档+未完成的放到issue里）
有空可以继续弄弄

2023-09-15 09:56 UTC, daonan233 commented
之前有一些网络请求问题，目前已经修改好了喵。

2023-09-15 10:08 UTC, daonan233 commented on src/pages/tools/mail.vue
> +    </view>
已经注释掉了，目前而且写好了原来的post功能，上线的时候也可以正常发送通知。
目前这个是可以正常查看所有通知的列表的
![](https://pic.imgdb.cn/item/65042cf0661c6c8e548e3df0.png)

2023-09-15 10:09 UTC, daonan233 commented on src/pages/tools/sendmail.vue
> +        >
这个还没做喵qwq，先搁置一下（现在还不上线

2023-09-23 05:49 UTC, FrogDar commented
![image](https://github.com/e-dialect/hinghwa-dict-uni-app/assets/20886330/990236f5-866d-4b17-9626-52aa8ee0d507)

你这还是过不了编译呀

2023-09-23 05:57 UTC, daonan233 commented
pages.json里面配置的问题？我这边路径能过以为可以了欸（

2023-09-24 01:09 UTC, daonan233 commented
#143 过编译了喵，就改了pages.json，可能之前上传前没保存吧（

2023-09-25 03:59 UTC, FrogDar requested changes

2023-09-25 03:59 UTC, FrogDar commented on src/pages.json
> +    },
emmm 之前不是给过几个路由么）） 还是调整到那个吧

2023-09-25 03:59 UTC, FrogDar commented on src/pages.json
> -    },
在这个PR里，不应该删掉这几个页面

2023-10-02 12:14 UTC, FrogDar commented
残留问题：没有区分发件箱和收件箱（虽然短期内可以暂时不区分）
但是大问题是：向下滚动时候没有分页加载

2023-10-27 12:24 UTC, FrogDar commented
为什么我的邮件列表还是有问题无法加载呢、

2023-10-31 06:32 UTC, FrogDar commented
![image](https://github.com/e-dialect/hinghwa-dict-uni-app/assets/20886330/1560ad3c-86e8-455e-bbad-314af26b61ca)

向下滚动确实会出现加载的按钮，但是加载的内容并不会直接更新

是数组更新了但是页面没更新？

2023-10-31 06:34 UTC, FrogDar commented on src/pages/mails/index.vue
> +      const concatEmails = this.emails.slice(page * 4, page * 4 + 4);
说实话，不太理解这段的逻辑）

2023-11-25 11:35 UTC, FrogDar approved these changes

2023-11-25 11:36 UTC, merged