feat(point): add points system
e-dialect/hinghwa-dict-uni-app pull request #182
Opened 2023-08-17 15:17 UTC by daonan233

This is a feature about points

2023-08-18 15:10 UTC, FrogDar requested changes
我没看到应该从哪里点开积分商城？

2023-08-18 15:10 UTC, FrogDar commented on src/pages.json
> +	  "path": "pages/users/me/pointmall",
路由改到 pages/products/index

2023-08-18 15:10 UTC, FrogDar commented on src/pages.json
> +	  "path": "pages/users/me/uploadgoods",
路由改到 pages/products/upload

2023-09-03 17:38 UTC, FrogDar requested changes
修复了一些问题，接下来就是急需完善功能就可以了

2023-09-03 17:38 UTC, FrogDar commented on src/pages/products/index.vue
> +      pageInfo: {},
需要设置默认值，否则空白页面时候显示有问题

2023-09-03 17:38 UTC, FrogDar commented on src/pages/products/index.vue
> +      </view>
加点什么样式？不说能买了 先弄的好看一点的展示页面

2023-09-03 17:38 UTC, FrogDar commented on src/pages/products/index.vue
> +    </view>
图标弄个上传之类的
然后条件编译，如果是微信小程序则不显示

2023-09-03 17:38 UTC, FrogDar commented on src/pages/products/upload.vue
> +        >
所有的这个文本款就感觉显示有点问题？
![image](https://github.com/e-dialect/hinghwa-dict-uni-app/assets/20886330/665f0ef6-b6f5-461b-b665-43cecff41205)

2023-09-03 17:38 UTC, FrogDar commented on src/pages/products/upload.vue
> +          <p>点击上传图片</p>
这个感觉有点问题、
简单点的话可以从头像那里去抄

2023-09-15 09:57 UTC, daonan233 commented on src/pages/products/upload.vue
> +          <p>点击上传图片</p>
好的，现在正在修改这个问题

2023-09-15 09:57 UTC, daonan233 commented on src/pages/products/upload.vue
> +        >
这边的点击上传文件有点问题，我去上传头像那边看看

2023-10-17 13:32 UTC, FrogDar requested changes

2023-10-17 13:32 UTC, FrogDar commented on src/pages/products/productDetail.vue
> +<template>
这个文件的名字直接叫details就行吧，没必要前面加一个product

2023-10-17 13:32 UTC, FrogDar commented on src/pages/users/me/points.vue
> +    },
为啥不用routers里的东东？

2023-10-17 13:32 UTC, FrogDar commented on src/routers/points.js
> +}
这个感觉都废了没有好好利用？

2023-10-17 13:32 UTC, FrogDar commented on src/services/point.js
> +export async function getMyPoints(id) {
```suggestion
export async function getMyPoints(id, page=1, pageSize=10) {
```

一般来说 page 和 pageSize 都是当参数吧？

2023-10-17 13:32 UTC, FrogDar commented on src/services/point.js
> +  return request.get(`/transactions?user=${id}&page=1&pageSize=10&action=earn,redeem&start_date=&end_date=`);
以及这个拼接不需要你手动操作吧，get的第二个参数传一个object应该就能实现
（固定只看第一页肯定是不合适吧？

2023-10-17 13:32 UTC, FrogDar commented on src/pages/products/index.vue
> +    },
挪到 routers 里

2023-10-17 13:32 UTC, FrogDar commented on src/services/point.js
> +}
现在这个接口还没实现分页是吧）
那先这样、之后再更新

2023-10-17 13:32 UTC, FrogDar commented on src/pages/products/history.vue
> +      });
挪一挪）

2023-10-17 13:32 UTC, FrogDar commented on src/pages/products/index.vue
> +    </view>
这个要判断一下，只有他是管理员身份才应该出现这个按钮
（或者目前把这个按钮注释掉，另开一个PR吧

2023-11-26 17:46 UTC, FrogDar commented on src/pages.json
> +      "path": "pages/products/productDetail",
这个的路由是 `pages/products/details?id=xx` 就行

2023-11-26 17:46 UTC, FrogDar commented on src/pages/users/me.vue
> +  font-size: 36 rpx;
这个有没有空格有影响么） 不太记得了

2023-11-27 11:09 UTC, FrogDar approved these changes

2023-11-27 11:15 UTC, merged