Feat word list
e-dialect/hinghwa-dict-uni-app pull request #193
Opened 2023-11-30 09:18 UTC by daonan233

2023-12-01 09:20 UTC, daonan233 commented on src/services/website.js
> +}
阿 这个是我加的吗？（有可能是之前看apifox以为做试卷的是这个接口（

2023-12-01 11:31 UTC, FrogDar commented on src/pages.json
> +	},
那肯定的呀，删了的话这里也删掉了

2023-12-01 11:32 UTC, FrogDar requested changes
冲突记得解决一下呀，拉下来合并一下

2023-12-01 11:37 UTC, daonan233 commented on src/pages/tools/index.vue
>  }
哎呀 ，忘了这个也有了（

2024-03-08 17:27 UTC, daonan233 commented
词单部分应该是整完了（

2024-03-09 05:21 UTC, lin594 commented on src/pages/tools/index.vue
>  }
这个在网页里没问题，但是在微信小程序里貌似会让样式出错？

2024-03-09 05:25 UTC, lin594 commented
![image](https://github.com/e-dialect/hinghwa-dict-uni-app/assets/20886330/2b346cfe-cf73-40cc-922c-bc605d8b0df2)

还有这个图片得更换一下？

2024-03-21 11:46 UTC, lin594 commented
@daonan233 快换图，快换图（然后就可以合并了）
@Topology2333 你也可以先试试看有没有什么地方用起来有问题可以提一提

2024-03-22 00:38 UTC, lin594 approved these changes

2024-03-22 00:38 UTC, lin594 commented on src/pages/tools/index.vue
> +          img: 'https://pic.imgdb.cn/item/65fc2d909f345e8d03fb4be6.png',
```suggestion
          img: 'https://cos.edialect.top/website/词单学习.png',
```

2024-03-22 00:41 UTC, lin594 requested changes

2024-03-22 00:41 UTC, lin594 commented on src/routers/word.js
> +}
这个东西感觉不太对吧？
到底是去词语页面还是词单页面呢？
但是路径感觉都不太对

2024-03-22 00:41 UTC, lin594 commented on src/services/website.js
> +} */
直接删除而非注释形式

2024-03-22 05:06 UTC, daonan233 commented on src/services/website.js
> +} */
两个都已删除

2024-03-22 06:55 UTC, lin594 approved these changes

2024-03-22 06:55 UTC, merged