feat(quizpaper):add feat quizpaper(thers's no real paper in database …
e-dialect/hinghwa-dict-uni-app pull request #202
Opened 2024-02-24 12:23 UTC by daonan233

…now)

2024-02-26 12:44 UTC, lin594 commented on package.json
> +    "element-plus": "^2.3.12",
怎么突然使用上了这个)

2024-02-26 12:45 UTC, lin594 requested changes

2024-02-26 12:45 UTC, lin594 commented on src/pages/quizzes/index.vue
> +  margin: 30 rpx 0;
30rpx 不要分开

2024-02-26 12:45 UTC, lin594 commented on src/pages/users/me.vue
>              <text class="text-grey">
啊？

2024-03-09 05:28 UTC, lin594 commented on src/pages/users/me.vue
>              <text class="text-grey">
我的文章里面怎么自动跳转到测试题里？
以及为何是`quizzset`

2024-03-09 06:04 UTC, lin594 commented
感觉还有不少工作量、、 不过可能需要和你本地的进度合并一波

2024-03-13 07:50 UTC, daonan233 commented on src/pages/quizzes/index.vue
> +  margin: 30 rpx 0;
这个问题是，用webstorm进行eslint --fix的时候会进行自动空两格，不知道是不是eslint版本的问题？

2024-03-13 07:54 UTC, daonan233 commented on src/pages/users/me.vue
>              <text class="text-grey">
之前没想好放哪的时候在这边作为入口测试的测试题页面，忘改回去了（
已经在本地改回去了，下次一并push

2024-03-13 08:12 UTC, lin594 commented on src/pages/quizzes/index.vue
> +  margin: 30 rpx 0;
因为rpx这个东西是中国人自创的（从微信小程序开始），所以你可以在webstorm里安装一些插件就能解决这个问题

2024-03-13 08:12 UTC, lin594 commented on src/pages/users/me.vue
>              <text class="text-grey">
我当时以为你已经搞的差不多，然后搞错了
所以做了很多修改，一定要和你本地先同步一下

2024-04-02 08:14 UTC, lin594 commented
等你准备好了就选一下那个 `ready for review`

2024-05-06 08:59 UTC, daonan233 commented
我在处理页面的时候有个数据持久化的问题。
我做了一个大答题卡页面，希望答完某道题之后对应题的方块颜色会变（比如没做是白色，对了是绿色，错了是橙色）。
但是每次回到答题卡页面之后onLoad都会重新初始化我用来判断的那个数组，所以我需要一个数据持久化库
我要不要在项目里引入这样一个库？比如VueX或者Pinia之类的

2024-07-08 03:30 UTC, lin594 commented
诶，所以这个PR是可以准备好提交了吗？

2024-07-08 03:34 UTC, daonan233 commented
我把这个语音的也在这里提交了（
这个可以merge了

2024-07-08 03:35 UTC, lin594 commented
> 我把这个语音的也在这里提交了（ 这个可以merge了

渣男 我不许） 这个让我怎么起分支名，你快拆开

2024-07-08 03:50 UTC, daonan233 commented
> > 我把这个语音的也在这里提交了（ 这个可以merge了
> 
> 渣男 我不许） 这个让我怎么起分支名，你快拆开

好好好（我下午拆一下

2024-07-08 08:52 UTC, lin594 commented
拆完之后顺便自测一下，我就假装相信你的自测结果） 然后一起发布版本了

2024-07-08 09:03 UTC, daonan233 commented
这个拆是什莫意思，我在这个新的提交里面只改了这个json.parse的问题，是指回退版本到上一次提交吗

2024-07-08 13:30 UTC, lin594 requested changes

2024-07-08 13:30 UTC, lin594 commented on src/const/urls.js
> +  : 'https://api.pxm.edialect.top';
比如这个就不能改

2024-07-08 13:30 UTC, lin594 commented on package.json
> +    "element-plus": "^2.3.12",
你其他地方真的有调用他嘛？

2024-07-08 13:30 UTC, lin594 commented on src/pages/quizzes/index.vue
> +                组卷测试
这是测试还是啥 改一下中文名称吧

2024-07-08 13:30 UTC, lin594 commented on src/pages/words/pronunciations/upload.vue
> +        pronunciation.source = res.url;
最好是回退一下，不回退也就算了

2024-07-08 13:49 UTC, daonan233 commented on src/pages/words/pronunciations/upload.vue
> +        pronunciation.source = res.url;
已在新上传版本中回退到JSOn.parse

2024-07-08 13:49 UTC, daonan233 commented on src/pages/quizzes/index.vue
> +                组卷测试
在新版本中已改成组卷答题（主要是上面也是 开始答题 感觉怪怪的（？

2024-07-08 13:50 UTC, daonan233 commented on src/pages/quizzes/index.vue
> +                组卷测试
然后这个elementplus，我git 带了这个package.json就推不上去（，所以这次更改没去掉这个

2024-07-08 14:22 UTC, lin594 commented on src/const/urls.js
> +  : 'https://api.pxm.edialect.top';
这个得调换回去呀，要不然出问题的

2024-07-08 14:23 UTC, lin594 commented on src/const/urls.js
> +  : 'https://api.pxm.edialect.top';
```suggestion
  ? 'https://api.pxm.edialect.top'
  : 'https://api.pxm.test.edialect.top';
```

2024-07-08 14:25 UTC, lin594 commented
<img width="492" alt="image" src="https://github.com/e-dialect/hinghwa-dict-uni-app/assets/20886330/a22f2e28-eeee-4d81-9e94-88aef2e3696b">

2024-07-08 14:32 UTC, daonan233 commented
![屏幕截图 2024-07-08 223138](https://github.com/e-dialect/hinghwa-dict-uni-app/assets/91860300/3dc35c0e-d9d6-4359-ac56-607c4d7cf17a)

这个好像是后端的问题？我这边是按apifox上面的写的

2024-07-08 14:33 UTC, lin594 commented
> ![屏幕截图 2024-07-08 223138](https://private-user-images.githubusercontent.com/91860300/346604380-3dc35c0e-d9d6-4359-ac56-607c4d7cf17a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0NDk0NDMsIm5iZiI6MTcyMDQ0OTE0MywicGF0aCI6Ii85MTg2MDMwMC8zNDY2MDQzODAtM2RjMzVjMGUtZDlkNi00MzU5LWFjNTYtNjA3YzRkN2NmMTdhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDE0MzIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YmY0MmI4ZjZmZmY0MDYzNjUyOTlmZDMyYWUyYjYyODk4ZGI0MzhjMGY0ZWYyY2NjYTcyZjg2NjUwYjBkNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._9_HdUphR8I91ZvYclY4BRMr27uNaBY8lG2ftsqh4wg)
> 
> 这个好像是后端的问题？我这边是按apifox上面的写的

@CapooL 你看看？

2024-07-08 14:34 UTC, lin594 commented
> 这个好像是后端的问题？我这边是按apifox上面的写的

如果正常请求返回回来是空，那会自动清空这个页面吗？

2024-07-08 14:37 UTC, daonan233 commented
> > 这个好像是后端的问题？我这边是按apifox上面的写的
> 
> 如果正常请求返回回来是空，那会自动清空这个页面吗？

会的，是在onLoad里面请求的，请求到就刷新该页面的数据，如果是空就是显示空
我可以现在加一个判断records长度的，如果是0就显示 当前用户没有答题记录 的提示
我现在加一下

2024-07-09 13:22 UTC, CapooL commented
![image](https://github.com/e-dialect/hinghwa-dict-uni-app/assets/111524029/2aa611b0-c187-4ea2-aee2-92cb4ca0de7e)
我这边试的感觉没问题
如果用户id没传或者格式不对（没有只包含数字）的话会返回400

2024-07-09 13:23 UTC, CapooL commented
> ![屏幕截图 2024-07-08 223138](https://private-user-images.githubusercontent.com/91860300/346604380-3dc35c0e-d9d6-4359-ac56-607c4d7cf17a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzA5ODAsIm5iZiI6MTcyMDUzMDY4MCwicGF0aCI6Ii85MTg2MDMwMC8zNDY2MDQzODAtM2RjMzVjMGUtZDlkNi00MzU5LWFjNTYtNjA3YzRkN2NmMTdhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDEzMTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZTI3MDdjYzhhMjEyZDBkNTlmMThhMzViZTNkMGRmZGE0OTdhNjY1MmIyNjNmYjFiZWNlMmEwMzQyOWNhM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MnnAqLvYSSCjRldcLFmlj3DyUrR5qBvmv7SS6asUIBU)
> 
> 这个好像是后端的问题？我这边是按apifox上面的写的

55哥这边user_id传的是数字编号还是用户名

2024-07-10 03:11 UTC, daonan233 commented
> > ![屏幕截图 2024-07-08 223138](https://private-user-images.githubusercontent.com/91860300/346604380-3dc35c0e-d9d6-4359-ac56-607c4d7cf17a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzA5ODAsIm5iZiI6MTcyMDUzMDY4MCwicGF0aCI6Ii85MTg2MDMwMC8zNDY2MDQzODAtM2RjMzVjMGUtZDlkNi00MzU5LWFjNTYtNjA3YzRkN2NmMTdhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDEzMTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZTI3MDdjYzhhMjEyZDBkNTlmMThhMzViZTNkMGRmZGE0OTdhNjY1MmIyNjNmYjFiZWNlMmEwMzQyOWNhM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MnnAqLvYSSCjRldcLFmlj3DyUrR5qBvmv7SS6asUIBU)
> > 这个好像是后端的问题？我这边是按apifox上面的写的
> 
> 55哥这边user_id传的是数字编号还是用户名

数字编号

2024-07-10 03:18 UTC, daonan233 commented
> > ![屏幕截图 2024-07-08 223138](https://private-user-images.githubusercontent.com/91860300/346604380-3dc35c0e-d9d6-4359-ac56-607c4d7cf17a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1MzA5ODAsIm5iZiI6MTcyMDUzMDY4MCwicGF0aCI6Ii85MTg2MDMwMC8zNDY2MDQzODAtM2RjMzVjMGUtZDlkNi00MzU5LWFjNTYtNjA3YzRkN2NmMTdhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA5VDEzMTEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZTI3MDdjYzhhMjEyZDBkNTlmMThhMzViZTNkMGRmZGE0OTdhNjY1MmIyNjNmYjFiZWNlMmEwMzQyOWNhM2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MnnAqLvYSSCjRldcLFmlj3DyUrR5qBvmv7SS6asUIBU)
> > 这个好像是后端的问题？我这边是按apifox上面的写的
> 
> 55哥这边user_id传的是数字编号还是用户名

不好意思，我这边自己的问题，我修改一下就提交

2024-07-10 06:09 UTC, lin594 commented
> 不好意思，我这边自己的问题，我修改一下就提交

现在返回请求不存在，这个也不合适吧  不应该是一个空列表嘛？

2024-07-12 02:02 UTC, daonan233 commented
> > 不好意思，我这边自己的问题，我修改一下就提交
> 
> 现在返回请求不存在，这个也不合适吧 不应该是一个空列表嘛？

  啊？我这边是显示为空啊（，是没登陆的情况下吗
![屏幕截图 2024-07-12 100111](https://github.com/user-attachments/assets/1d163953-3ad6-4e11-88c2-61fed19240fe)

2024-07-12 02:29 UTC, daonan233 commented
> > > 不好意思，我这边自己的问题，我修改一下就提交
> > 
> > 
> > 现在返回请求不存在，这个也不合适吧 不应该是一个空列表嘛？
> 
> 啊？我这边是显示为空啊（，是没登陆的情况下吗 ![屏幕截图 2024-07-12 100111](https://private-user-images.githubusercontent.com/91860300/348063170-1d163953-3ad6-4e11-88c2-61fed19240fe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NTE1MzYsIm5iZiI6MTcyMDc1MTIzNiwicGF0aCI6Ii85MTg2MDMwMC8zNDgwNjMxNzAtMWQxNjM5NTMtM2FkNi00ZTExLTg4YzItNjFmZWQxOTI0MGZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDAyMjcxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMDRhZTBlZTc2NGE4Mzc5N2Y0Njg5MjNiNTE3ZmQxYTE4NGUyMDg2OTM1MzAxNzkyOTk5Y2E3ZTU3MmFhMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b5H9FrsVoTfRkPavfQ2bZu-mjtl3xIsKlAIBwBpdnio)

已更正此问题，增加：在没有登陆的情况下点击组卷答题按钮会跳出提示框并跳转到登陆界面。
![屏幕截图 2024-07-12 102707](https://github.com/user-attachments/assets/75406fc3-53c9-4f83-9bb1-f4ca90708c89)

2024-07-15 08:45 UTC, lin594 approved these changes

2024-07-15 08:46 UTC, merged