feat: show unread mails in user page
e-dialect/hinghwa-dict-uni-app pull request #204
Opened 2024-03-07 07:19 UTC by Topology2333

close #195

2024-03-07 12:59 UTC, Topology2333 commented
> This PR is deployed at https://orange-cliff-0b1e10000-204.eastasia.2.azurestaticapps.net

这是啥意思）

2024-03-08 07:13 UTC, lin594 commented
> 这是啥意思）

把你写的东西自动部署出来，方便测试

2024-03-08 07:16 UTC, lin594 requested changes

2024-03-08 07:16 UTC, lin594 commented on package.json
> +    "lint-windows": "eslint --ext .js,.vue src --max-warnings 0 --fix",
这个应该叫`lint-fix`吧，怎么会想到叫做`lint-windows`的

2024-03-08 07:16 UTC, lin594 commented on .gitattributes
> +* text eol=lf
一定要有吗）删了不行嘛）

2024-03-08 07:24 UTC, Topology2333 commented on package.json
> +    "lint-windows": "eslint --ext .js,.vue src --max-warnings 0 --fix",
我当时的想法是在类 Unix 系统上一般不会报 CRLF 的错
这个工具相当于只在 Windows 系统中检查代码时用用得了

---

不过听你这么一说好像确实叫 `lint-fix` 合理些

2024-03-08 07:27 UTC, lin594 commented on package.json
> +    "lint-windows": "eslint --ext .js,.vue src --max-warnings 0 --fix",
但是lint一般不是crlf的问题啦，也包括比如换行啊，单引号双引号，标签内元素顺序等等的其他规范

2024-03-08 07:28 UTC, Topology2333 commented on .gitattributes
> +* text eol=lf
是有必要有的

2024-03-08 07:35 UTC, Topology2333 commented on .gitattributes
> +* text eol=lf
参考 [git 文档](https://git-scm.com/docs/gitattributes#:~:text=While%20Git%20normally%20leaves%20file%20contents%20alone%2C%20it%20can%20be%20configured%20to%20normalize%20line%20endings%20to%20LF%20in%20the%20repository%20and%2C%20optionally%2C%20to%20convert%20them%20to%20CRLF%20when%20files%20are%20checked%20out.) 或者 [问答](https://stackoverflow.com/questions/73086622/is-a-gitattributes-file-really-necessary-for-git)

简单来说就是项目配置的一部分，统一不同开发平台在作出修改提交时候遵循的配置。。。不需要每一个开发者每次都因为某项目要用某一种格式而去修改本地开发环境的配置。。。

2024-03-08 07:42 UTC, Topology2333 commented on .gitattributes
> +* text eol=lf
如果觉得没用也可以删。。但最好写一个文档指导一下必要的 lint 工具和 git 配置，否则每次有人加入都得重新问，并修改自己的配置，很不方便的。

2024-03-08 07:54 UTC, lin594 commented on .gitattributes
> +* text eol=lf
那就留着吧） 至于文档如果你有精力的话可以操作一下x

2024-03-08 07:55 UTC, lin594 approved these changes

2024-03-08 07:57 UTC, merged