fix(article): use button in article edit page
e-dialect/hinghwa-dict-uni-app pull request #209
Opened 2024-03-14 12:58 UTC by Topology2333

2024-03-14 15:14 UTC, lin594 requested changes
其他几个更改是为何？不太理解（可能也是因为我没看过他的原图

2024-03-14 15:14 UTC, lin594 commented on src/pages/articles/edit.vue
>          >
之前这个功能不能用？如果你要改的话，可以把这里改成一个button样式更符合他的语义

2024-03-15 01:32 UTC, Topology2333 commented on src/pages/articles/edit.vue
>          >
之前是点击预览，无法显示。
具体而言是这个页面
![image](https://github.com/e-dialect/hinghwa-dict-uni-app/assets/118144168/d87d7e6d-5edb-4551-bbfd-b0d93b55c521)
后来我又发现因为是 `input`，所以甚至原来的 `预览` 和 `上传` 的文字部分居然可以被修改……

2024-03-15 01:34 UTC, Topology2333 commented on src/pages/articles/edit.vue
>          >
![image](https://github.com/e-dialect/hinghwa-dict-uni-app/assets/118144168/70232ce4-cef4-4fec-a7c3-35ec29d0e4dd)

2024-03-15 01:36 UTC, Topology2333 commented
> 其他几个更改是为何？不太理解（可能也是因为我没看过他的原图

其他几个更改我也不晓得，应该是自动改的
我只手动改了一

2024-03-15 07:05 UTC, lin594 commented on src/pages/articles/edit.vue
>          >
之前的disable就是为了防止这一点的，特意让他不能修改
但是没想到在你那里直接也让他无法点击

2024-03-15 07:06 UTC, lin594 commented
> 其他几个更改我也不晓得，应该是自动改的 我只手动改了一

其实就是在你的那个分支里把这些都改了，你要不把这个页面的这个修改复制出来，重新发起一个PR吧

2024-03-15 09:12 UTC, Topology2333 commented
> > 其他几个更改我也不晓得，应该是自动改的 我只手动改了一
> 
> 其实就是在你的那个分支里把这些都改了，你要不把这个页面的这个修改复制出来，重新发起一个PR吧

彳亍

2024-03-15 09:48 UTC, Topology2333 commented
> > 其他几个更改我也不晓得，应该是自动改的 我只手动改了一
> 
> 其实就是在你的那个分支里把这些都改了，你要不把这个页面的这个修改复制出来，重新发起一个PR吧

但是我每次克隆下来 e 方言主仓库，这四个文件都是自动处于被更改的状态，我有理由怀疑是仓库出了点问题）

复现环境：Windows 11或者 Ubuntu 20.04 或者 MacBook Air，用 ssh 克隆和用 http 克隆都试过，有没有打开编辑器也都试过。
在未进行任何更改的情况下进入文件夹，直接 git status 都会显示其余四个被修改的文件

2024-03-15 09:50 UTC, Topology2333 commented on src/pages/articles/edit.vue
>          >
> 之前的disable就是为了防止这一点的，特意让他不能修改 但是没想到在你那里直接也让他无法点击

可恶，什么叫 `在我这里` 。明明在哪里都没法点击好吧、、😒

2024-03-15 09:56 UTC, lin594 commented
我自己用的好好的）



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 15, 2024 17:51 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [e-dialect/hinghwa-dict-uni-app] fix: fix markdown viewer (PR#209)




 
@Topology2333 commented on this pull request.
 
 
In src/pages/articles/edit.vue:
 &gt;          <input            class="extend text-grey" -          disabled            :value="inPreviewStatus?'编辑':'预览'"            @tap="inPreviewStatus=!inPreviewStatus"          &gt;   
之前的disable就是为了防止这一点的，特意让他不能修改 但是没想到在你那里直接也让他无法点击
  
可恶，什么叫 在我这里 。明明在哪里都没法点击好吧、、😒
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;

2024-03-15 11:14 UTC, charlie0129 commented
那四个文件是 Line Ending 的问题，包括图片，里面是 CRLF

2024-03-15 12:20 UTC, Topology2333 commented
> 那四个文件是 Line Ending 的问题，包括图片，里面是 CRLF ，把它都改成 LF 吧。

我貌似知道其中的一部分原因了。有我写 `.gitattribute` 的锅。
图片是二进制文件，所以会出现类似于以下的提示：

```md
We’ve detected the file has mixed line endings. When you commit changes we will normalize them to Windows-style (CRLF).
```

想到的解决方案是在 `.gitattribute` 里加上

```
*.jpg binary
*.png binary
```

但是对于 workflow 里的机制我还不是很清楚

2024-03-16 15:39 UTC, lin594 commented
> 但是对于 workflow 里的机制我还不是很清楚

这个应该单纯是当时那个文件是用crlf储存的而已，没事你把它改成lf就好
（只不过不要和fix Markdown在同一个pr呗

2024-03-21 11:45 UTC, merged