fix: fix icon display error in qq miniprogram
e-dialect/hinghwa-dict-uni-app pull request #213
Opened 2024-04-12 13:35 UTC by Topology2333

close #210

2024-04-13 05:18 UTC, lin594 requested changes

2024-04-13 05:18 UTC, lin594 commented on .github/workflows/receive-pr.yml
> +          npm audit fix --force
我一点也不能理解你的逻辑，你不应该强制修复之后提交更改嘛？为什么是在workflow里写

2024-04-13 12:21 UTC, Topology2333 commented on .github/workflows/receive-pr.yml
> +          npm audit fix --force
你说的是 package.json 吧，我今天又检查了一下，我发现如果是 build 就会出错，但是用 dev 编译出来的就是正常的，所以我最新的代码改成了 dev

2024-04-13 13:16 UTC, Topology2333 commented on .github/workflows/receive-pr.yml
> +          npm audit fix --force
而且只改 package.json 目前来看没法解决这个问题（）

2024-04-13 15:37 UTC, lin594 commented on .github/workflows/receive-pr.yml
> +          npm audit fix --force
build 和 dev 他的编译逻辑是不一样的，不能简单把dev换成build来解决这个问题

2024-04-14 01:54 UTC, Topology2333 commented on .github/workflows/receive-pr.yml
> +          npm audit fix --force
但是按[这里](https://zh.uniapp.dcloud.io/quickstart.html#:~:text=%E7%9B%AE%E5%89%8D%E4%BD%BF%E7%94%A8npm,%E5%80%BC%E4%B8%BA%20production%E3%80%82)的说法，dev 也是可以用的，只不过有断点、压缩、process.env.NODE_ENV的区别……
况且本机选择 dev 编译出来的玩意确确实实是可以运行的，即使把 dev 的 process 关了

2024-04-14 01:56 UTC, Topology2333 commented on .github/workflows/receive-pr.yml
> +          npm audit fix --force
我觉得我应该在 dev 的编译完成后把这个进程关了，这样应该就没什么问题了

2024-05-15 06:14 UTC, lin594 commented on .github/workflows/receive-pr.yml
> +          npm audit fix --force
那还得改一些别的东西， 还是小小钻研一下为什么有这个区别）

2024-05-15 06:18 UTC, Topology2333 commented on .github/workflows/receive-pr.yml
> +          npm audit fix --force
行

2024-07-08 03:31 UTC, closed without merging