fix: fix searchCharacter function
e-dialect/hinghwa-dict-uni-app pull request #89
Opened 2022-11-21 08:48 UTC by zzy2695s

close #80

2022-11-21 08:50 UTC, zzy2695s commented
![image](https://user-images.githubusercontent.com/106298834/203006242-d9295a3f-893e-4103-b527-a66a503d4199.png)
改成了v2接口，修好了

2022-11-21 08:55 UTC, FrogDar requested changes
好像显示又没有对齐了？

2022-11-21 08:55 UTC, FrogDar commented on src/pages/basics/search/search.vue
> +          if (res.statusCode == 200) {
```suggestion
          if (res.statusCode === 200) {
```

2022-11-21 08:55 UTC, FrogDar commented on src/pages/basics/search/search.vue
>          },
改都改了）顺便用service重构这里吧）

2022-11-21 12:45 UTC, zzy2695s commented on src/pages/basics/search/search.vue
>          },
收到qaq 那其他几个也顺便一起吧？orz

2022-11-21 12:46 UTC, zzy2695s commented on src/pages/basics/search/search.vue
> +          if (res.statusCode == 200) {
欸怎么回事？好的好的我改下

2022-11-26 09:16 UTC, FrogDar commented on src/pages/basics/search/search.vue
> +        });
如果是500的画，默认就应该会弹出吧？应当不需要手动写这个？

2022-11-26 09:16 UTC, FrogDar commented on src/pages/basics/search/search.vue
> +        uni.hideLoading();
为啥要hide

2022-11-26 09:16 UTC, FrogDar commented on src/pages/basics/search/search.vue
> +        this.articles = res1.articles;
从 key 到具体文章列表，这好像出现了不止一次？其实可以放在一起吧（算了 另外开一个issue解决得了x）

2022-11-26 11:22 UTC, zzy2695s commented on src/pages/basics/search/search.vue
> +        });
okok有道理

2022-11-26 11:35 UTC, zzy2695s commented on src/pages/basics/search/search.vue
> +        uni.hideLoading();
哦哦我看前面有uni.showloading就加上了（是已经封装的函数就不需要写show hideloading了嘛 因为request里有了？ 不知道理解的对不对。

2022-11-26 11:36 UTC, zzy2695s commented on src/pages/basics/search/search.vue
> +        this.articles = res1.articles;
好的好的 就是把这个函数封装了？

2022-11-26 14:28 UTC, zzy2695s commented
- 修了词语界面底部分割线，之前有点问题
- 搜索文章函数封装了(不知道格式对不对
- 文章显示换成了组件

2022-11-26 14:29 UTC, zzy2695s commented
![image](https://user-images.githubusercontent.com/106298834/204093874-3c225d22-3c8d-4c57-93ce-bac0d6d03ee0.png)
![image](https://user-images.githubusercontent.com/106298834/204093883-6f09231a-87d9-4e46-9f5e-8dee542d587f.png)
还添加了搜索内容为空的提示栏

2022-11-26 14:32 UTC, zzy2695s commented
但还是有个问题，就是搜索单字这里搜索的结果没有内容他的数组不为空，显示undefinded，有点奇怪
![d7224ed80fd7b4f722929b9ed842159](https://user-images.githubusercontent.com/106298834/204094034-ae3b69c2-a8b2-43bc-91c5-feb17bf51d56.png)

2022-11-26 14:33 UTC, zzy2695s commented
但还是有个问题，就是搜索单字这里搜索的结果没有内容他的数组不为空，显示undefined，有点奇怪
![d7224ed80fd7b4f722929b9ed842159](https://user-images.githubusercontent.com/106298834/204094082-a963b750-9157-4cc7-b9ae-6e26b05e8474.png)

2022-11-26 15:46 UTC, FrogDar commented on src/pages/basics/search/search.vue
> +        if (res.characters[0].characters.length === 0) {
```suggestion
        if (res.characters.length === 0) {
```

2022-11-26 15:46 UTC, FrogDar commented on src/pages/basics/search/search.vue
> +        if (res.characters[0].characters.length === 0) {
我感觉这个地方应该是这个吧？

2022-11-27 02:00 UTC, zzy2695s commented on src/pages/basics/search/search.vue
> +        if (res.characters[0].characters.length === 0) {
嗯嗯可以啦

2022-11-28 10:41 UTC, FrogDar approved these changes

2022-11-28 10:42 UTC, merged